### ISSUE TITLE
is test 5-8 on 2020_qualification/fuelstation wrong?

### ISSUE THREAD

**Issue by lutetjeff** [noisg/sg_noi_archive#7]
(issue at 2020_qualification/tasks/fuelstation/tests/5-8.out)

expected output is 914374022, which is the final distance. this doesn't make sense.
I got 658994055, but it could as well be literally anything lol

**Comment by btzy** [comment]
Note that the task statement states that "F refers to the amount of fuel (in litres) that Pengu **started** with".  In general, F would not be equal to the amount of fuel remaining when Pengu arrives at a fuel station.

Since all the B_i are strictly less than all the X_i, the only way to reach the destination is to start with enough fuel to cover the whole distance.
